<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Portfolio - Teddy Marie-louise</title>
    <link rel="stylesheet" href="style.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Playfair+Display:ital,wght@0,600;0,700;1,600&family=Montserrat:wght@400;500;600&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossorigin="anonymous">


</head>
<body>

<nav class="navbar navbar-expand-lg bg-body-tertiary sticky-top">
    <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
    <li class="nav-item">
        <a class="nav-link active" aria-current="page" href="#presentation">Présentation</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="#formations">Formations</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="#travail">Mon travail</a>
    </li>
        <li class="nav-item">
        <a class="nav-link" href="#contact-section">Contact</a>
        </li>
    </ul>
    </div>
    </div>
</nav>

    <section id="presentation" class="hero">
        <div class="image-placeholder"></div>
        <div class="hero-content">
            <h1>Teddy<br>Marie-louise</h1>
            <span class="subtitle">Étudiant en B1 Architecte en Logiciels Performants et Sécurisés</span>
            <p>Je suis un étudiant en programmation basé sur Paris. Mes spécialités compren²²²nent le développement de logiciel, de site web et la gestion de base de données.</p>
        </div>
    </section>

    <section id="formations" class="formations">
        <div class="img-container">
            </div>
        <div class="formations-content">
            <h2>Mes formations</h2>
            <ul class="formations-list">
                <li>École 89 (B1 en Architecte en Logiciels Performants et Sécurisés) 2025-2026</li>
                <li>Université Gustave Eiffel (L2 STAPS APAS) 2022-2025</li>
                <li>Lycée Jean Vilar (Baccalauréat général, spécialité Anglais Monde Contemporain et Éducation Physique, Pratiques et Culture Sportives)</li>
            </ul>
        </div>
    </section>

    <section id="collaborations" class="collaborations">
        <h2>J'ai travaillé avec</h2>
        <div class="logos">
            <span>STELLA</span>
            <span style="font-family: 'Brush Script MT', cursive;">ACCELIIS</span>
            <span style="font-family: 'Impact', sans-serif; font-weight: normal;">ADAGIO</span>
            <span style="font-weight: bold; letter-spacing: 2px;">HONDA</span>
        </div>
    </section>

    <section id ="travail" class="travail">
        <div class="travail-header">
            <h2>Mon travail</h2>
            <p>Voici différents projets que j'ai réalisé durant mes études et d'autres projets extra-scolaire</p>
        </div>
        
        <button class="btn-filtre">FILTRE</button>

        <div class="grid-projets">
            <div class="carte-projet">
                <div class="image-placeholder"></div>
                <h3>NOM DU PROJET</h3>
                <div class="tags">
                    <span class="tag">DESIGN</span>
                    <span class="tag">SITE WEB</span>
                    <span class="tag">CODE APPLICATION</span>
                </div>
            </div>

            <div class="carte-projet">
                <div class="image-placeholder"></div>
                <h3>NOM DU PROJET</h3>
                <div class="tags">
                    <span class="tag">DESIGN</span>
                    <span class="tag">LOGICIEL</span>
                    <span class="tag">BASE DE DONNÉES</span>
                </div>
            </div>

            <div class="carte-projet">
                <div class="image-placeholder"></div>
                <h3>NOM DU PROJET</h3>
                <div class="tags">
                    <span class="tag">PYTHON</span>
                    <span class="tag">SCRIPT</span>
                    <span class="tag">WEB SCRAPING</span>
                </div>
            </div>
        </div>
    </section>

    <section class="contact-section">
        <div class="contact-info">
            <h2>Me contacter</h2>
            <ul class="contact-list">
                <li>
                    <svg fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 8l7.89 5.26a2 2 0 002.22 0L21 8M5 19h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z"></path></svg>
                    <a href="mailto:Teddy.marielouise77@gmail.com">Teddy.marielouise77@gmail.com</a>
                </li>
                <li>
                    <svg fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 5a2 2 0 012-2h3.28a1 1 0 01.948.684l1.498 4.493a1 1 0 01-.502 1.21l-2.257 1.13a11.042 11.042 0 005.516 5.516l1.13-2.257a1 1 0 011.21-.502l4.493 1.498a1 1 0 01.684.949V19a2 2 0 01-2 2h-1C9.716 21 3 14.284 3 6V5z"></path></svg>
                    06.26.42.27.39
                </li>
                <li>
                    <svg fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M16 8a6 6 0 016 6v7h-4v-7a2 2 0 00-2-2 2 2 0 00-2 2v7h-4v-7a6 6 0 016-6zM2 9h4v12H2z"></path><circle cx="4" cy="4" r="2" stroke="currentColor" stroke-width="2"></circle></svg>
                    <a href="https://linkedin.com/" target="_blank">Teddy Marie-Louise linkedin</a>
                </li>
                <li>
                    <svg fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17.657 16.657L13.414 20.9a1.998 1.998 0 01-2.827 0l-4.244-4.243a8 8 0 1111.314 0z"></path><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 11a3 3 0 11-6 0 3 3 0 016 0z"></path></svg>
                    Paris/Seine-et-Marne
                </li>
            </ul>
            <p class="merci">Merci pour votre temps</p>
        </div>
        <div class="image-placeholder"></div>
    </section>


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js" integrity="sha384-FKyoEForCGlyvwx9Hj09JcYn3nv7wiPVlz7YYwJrWVcXK/BmnVDxM+D2scQbITxI" crossorigin="anonymous"></script>
</body>
</html>